/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package proyvmm;

/**
 *
 * @author Daniel
 */
public class frmVentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmVentanaPrincipal
     */
    public frmVentanaPrincipal() {
        initComponents();
        jToggleButton1.setText("OFF");
        txtPaneDescripcion.setVisible(false);
        txtPaneDescripcion.setText("Elija un área a su gusto...");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnArreglos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPaneDescripcion = new javax.swing.JTextPane();
        btnBancoProblemas = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        btnSudoku = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnArreglos.setText("Arreglos");
        btnArreglos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnArreglosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnArreglosMouseExited(evt);
            }
        });
        btnArreglos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArreglosActionPerformed(evt);
            }
        });

        txtPaneDescripcion.setEditable(false);
        jScrollPane1.setViewportView(txtPaneDescripcion);

        btnBancoProblemas.setText("Banco de problemas");

        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        btnSudoku.setText("Sudoku");
        btnSudoku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSudokuActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/salir-de-gnome-icono-7637-96.png"))); // NOI18N
        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnArreglos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBancoProblemas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSudoku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnArreglos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBancoProblemas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSudoku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnArreglosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArreglosActionPerformed
        frmContenido ventanaArreglos=new frmContenido();
        ventanaArreglos.setVisible(true);
        ventanaArreglos.setResizable(false);
        ventanaArreglos.setLocationRelativeTo(null);
        ventanaArreglos.setDefaultCloseOperation(frmVentanaPrincipal.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnArreglosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnArreglosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArreglosMouseEntered
        txtPaneDescripcion.setText("Genera una ventana nueva con varios items, ProyVector, ProyMatriz, y otras fichas relacionadas al tema de arreglos");
    }//GEN-LAST:event_btnArreglosMouseEntered

    private void btnArreglosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnArreglosMouseExited
        txtPaneDescripcion.setText("Elija un área a su gusto...");
    }//GEN-LAST:event_btnArreglosMouseExited

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        if (jToggleButton1.isSelected()){
            txtPaneDescripcion.setVisible(true);
            jToggleButton1.setText("ON");
        }
        else{
            txtPaneDescripcion.setVisible(false);
            jToggleButton1.setText("OFF");
        }
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void btnSudokuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSudokuActionPerformed
        frmSudoku ventanaSudo=new frmSudoku();
        frmPropiedadesSudo ventanaPropi=new frmPropiedadesSudo();
        ventanaSudo.setVisible(true);
        ventanaSudo.setLocationRelativeTo(this);
        ventanaSudo.setResizable(false);
        ventanaSudo.setDefaultCloseOperation(frmVentanaPrincipal.DISPOSE_ON_CLOSE);
        ventanaPropi.setVisible(true);
        ventanaPropi.setLocation(326, 195);
        ventanaPropi.setResizable(false);
        ventanaPropi.setDefaultCloseOperation(frmVentanaPrincipal.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSudokuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentanaPrincipal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArreglos;
    private javax.swing.JButton btnBancoProblemas;
    private javax.swing.JButton btnSudoku;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTextPane txtPaneDescripcion;
    // End of variables declaration//GEN-END:variables
}
